Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"
  config.vm.hostname = "db01"
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.network "forwarded_port", guest: 3306, host:3306
end